on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: cn
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: build zip
        run: |
          apt-get update && apt-get install -y zip && rm -rf /var/lib/apt/lists/*
          zip -r fileadmin.zip *
      - name: upload to cos
        uses: xiaoqidun/gocos@main
        with:
          secret_id: ${{ secrets.cos_secret_id }}
          secret_key: ${{ secrets.cos_secret_key }}
          bucket_url: ${{ secrets.cos_bucket_url }}
          source_path: fileadmin.zip
          target_path: product